CREATE TABLE MAINMEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_ID VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(25) NOT NULL,
	PHONE_NUMBER VARCHAR2(20),
	MEMBER_ADDRESS VARCHAR2(50),
	DELETE_YN CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
);

SELECT * FROM MAINMEMBER;

CREATE SEQUENCE SEQ_MAIN_MEMBER_NO
START WITH 1
INCREMENT BY 1;

INSERT INTO MAINMEMBER
VALUES(NO,ID,PW,NAME,PHONE,ADDRESS,SSN,DEL);
