CREATE TABLE MEMBER(
	MEMBER_NO NUMBER,
	MEMBER_ID VARCHAR2(30) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(30) NOT NULL,
	PHONE_NUMBER VARCHAR2(20),
	DELETE_YN CHAR(1) DEFAULT 'N' CHECK(DELETE_YN IN('Y','N'))
);

DROP TABLE MEMBER;

COMMENT ON COLUMN MEMBER.MEMBER_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.MEMBER_ID IS '아이디';
COMMENT ON COLUMN MEMBER.MEMBER_PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.PHONE_NUMBER IS '핸드폰번호';
COMMENT ON COLUMN MEMBER.DELETE_YN IS '삭제여부';

CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 100
INCREMENT BY 100;

DROP SEQUENCE SEQ_MEMBER_NO;

SELECT SEQ_MEMBER_NO.NEXTVAL FROM DUAL;

INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step1','step11',NULL,NULL);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step2','step22','010-1111-2222',NULL);
INSERT INTO MEMBER VALUES(SEQ_MEMBER_NO.NEXTVAL, 'step3','step33',NULL,NULL);

SELECT * FROM MEMBER;