-- 시퀀스 생성
CREATE SEQUENCE SEQ_MEMBER_NO NOCACHE; -- 회원번호
CREATE SEQUENCE SEQ_BOARD_NO NOCACHE; -- 게시글번호
CREATE SEQUENCE SEQ_COMMENT_NO NOCACHE; -- 댓글번호

-- MEMBER 테이블에 INSERT하기
INSERT INTO MEMBER 
VALUES(SEQ_MEMBER_NO.NEXTVAL,
	'mem1@gmail.com',
	'qwer123',
	'1번회원',
	'01012341234',
	'서울시 중구',
	DEFAULT,DEFAULT);

COMMIT;

-- 이메일, 비밀번호가 일치하는 회원의
-- 닉네임, 전화번호, 주소 수정
UPDATE MEMBER
SET MEMBER_NICKNAME = '변경된 닉네임',
	MEMBER_TEL = '01011112222',
	MEMBER_ADDRESS = '경기도 수원시'
WHERE MEMBER_EMAIL = 'mem1@gmail.com'
AND MEMBER_PW = 'qwer123';

ROLLBACK;

DELETE FROM MEMBER
WHERE MEMBER_EMAIL = 'mem1@gmail.com'
AND MEMBER_PW = 'qwer1234';

ROLLBACK;


UPDATE MEMBER 
SET MEMBER_PW = '입력받은 뉴 비번'
WHERE MEMBER_EMAIL = 'mem1@gmail.com'
AND MEMBER_PW = 'qwer123';


SELECT * FROM MEMBER;


-- 로그인
SELECT MEMBER_NO , MEMBER_NICKNAME , MEMBER_TEL , MEMBER_ADDRESS ,
		TO_CHAR(ENROLL_DATE,'YYYY"년" MM"월" DD"일" HH24:MI:SS') ENROLL_DATE 
FROM MEMBER
WHERE MEMBER_EMAIL = ?
AND MEMBER_PW = ?
AND MEMBER_DEL_FL = 'N';

-- member 테이블 전체조회
SELECT * FROM MEMBER
--ORDER BY MEMBER_NO ; 오름 차순
ORDER BY MEMBER_NO DESC; -- 내림 차순

UPDATE MEMBER
SET MEMBER_NICKNAME = '별명',
MEMBER_TEL = '0'
WHERE MEMBER_NO = 6;
				
				
-- 회원 탈퇴
UPDATE MEMBER
SET MEMBER_DEL_FL = 'Y'
WHERE MEMBER_NO = 6
AND MEMBER_PW = 'qwer1234';
COMMIT;

SELECT * FROM BOARD;
-- board 테이블 insert
-- 실행 후 commit/rollback 
INSERT INTO BOARD
VALUES(SEQ_BOARD_NO.NEXTVAL, 'BOARD_TITLE', 'BOARD_CONTENT',DEFAULT,DEFAULT,DEFAULT,6)
;
COMMIT;

SELECT * FROM BOARD;
--        // 게시글 번호를 입력 받아 일치하는 게시글의
--        // 제목, 내용, 작성일, 조회수, 작성자번호, 작성자 닉네임 조회
--        // 단, 삭제되지 않은 게시글만 조회 가능(BOARD_DEL_FL = 'N')
SELECT BOARD_TITLE, BOARD_CONTENT , TO_CHAR(B_CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') B_CREATE_DATE, READ_COUNT , MEMBER_NO , MEMBER_NICKNAME
FROM BOARD
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_NO = 3;

UPDATE BOARD 
SET READ_COUNT = READ_COUNT + 1
WHERE BOARD_NO = 3;

ROLLBACK;


SELECT BOARD_NO , BOARD_TITLE , B_CREATE_DATE , READ_COUNT , MEMBER_NO , MEMBER_NICKNAME
FROM BOARD
JOIN MEMBER USING(MEMBER_NO)
WHERE BOARD_DEL_FL = 'N'
AND BOARD_NO = 6
ORDER BY BOARD_NO DESC;



SELECT *
FROM BOARD
WHERE BOARD_NO = 6;

ROLLBACK;

UPDATE BOARD
SET BOARD_DEL_FL = 'Y'
WHERE BOARD_NO = 6;

SELECT COUNT(*) FROM BOARD
WHERE BOARD_NO = 6
AND MEMBER_NO = 8;

UPDATE BOARD
SET BOARD_TITLE = '',
BOARD_CONTENT = ''
WHERE BOARD_NO = 6;

ALTER TABLE MAINMEMBER 
MODIFY (PHONE_NUMBER VARCHAR2(13));

ALTER TABLE MAINMEMBER 
MODIFY (MEMBER_SSN VARCHAR2(14) NOT NULL);


